src/PasswordManager/Controllers/ApiController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using PasswordManager.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;



namespace PasswordManager.Controllers
{
    [Authorize]
    public class ApiController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser>_userManager;

        public ApiController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }
//Index - Returns all of authenticated user's Site objects
        public async Task<IActionResult> Index()
        {
            ViewBag.ApiIndex = true;
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            return View(_db.Apis.Where(x => x.User.Id == currentUser.Id));
        }
//Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Api api)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            api.User = currentUser;
            _db.Apis.Add(api);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
//Edit
        public IActionResult Edit(int id)
        {
            var thisApi = _db.Apis.FirstOrDefault(api => api.Id == id);
            return View(thisApi);
        }
        [HttpPost]
        public IActionResult Edit(Api api)
        {
            _db.Entry(api).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        
//Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisApi = _db.Apis.FirstOrDefault(api => api.Id == id);
            _db.Apis.Remove(thisApi);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/PasswordManager/Controllers/SiteController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using PasswordManager.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace PasswordManager.Controllers
{
    [Authorize]
    public class SiteController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public SiteController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }
//Index - Returns all of authenticated user's Site objects
        public async Task<IActionResult> Index()
        {
            ViewBag.SiteIndex = true;
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            return View(_db.Sites.Where(x => x.User.Id == currentUser.Id));
        }
//Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Site site)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            site.User = currentUser;
            site.Password = Site.GeneratePassword();
            _db.Sites.Add(site);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
//Edit
        public IActionResult Edit(int id)
        {
            var thisSite= _db.Sites.FirstOrDefault(sites => sites.Id == id);
            return View(thisSite);
        }
        [HttpPost]
        public IActionResult Edit(Site site)
        {
            _db.Entry(site).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
//Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisSite= _db.Sites.FirstOrDefault(sites => sites.Id == id);
            _db.Sites.Remove(thisSite);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/PasswordManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PasswordManager</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="~/js/site.js"></script>
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            @Html.ActionLink(@User.Identity.Name, "Index", "Account")
                        </li>
                        <li>
                            @Html.ActionLink("Log off", "Index", "Account")
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("Log in", "Login", "Account") 
                        </li>
                        <li>
                            @Html.ActionLink("Register", "Register", "Account")
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="navbar navbar-left">
        <div class="nav-content">
            <h3>@Html.ActionLink("Passwords", "Index", "Site", new { @class = "nav-link" })</h3>
            @if (ViewBag.SiteIndex == true)
            {
                <h4>@Html.ActionLink("Create Password", "Create", "Site")</h4>
                    <h4 class="editSite">Edit Passwords</h4>
            }
            <hr />
            <h3>@Html.ActionLink("APIs", "Index", "Api")</h3>
             @if(ViewBag.ApiIndex == true)
             {
                 <h4>@Html.ActionLink("Create API", "Create", "Api")</h4>
                 <h4 class="editApi">Edit Passwords</h4>
             }
        </div>   
    </div>
    <div class="container body-content">
        <div class="render-body">
            @RenderBody()
        </div>
    </div>
</body>
</html>